### PR TITLE
fix assertion in get_constrs

### LINKED ISSUE #142: Off-by-one in assertion error when retrieving constraints
The assertion in `get_constrs` here: https://github.com/JuliaOpt/Gurobi.jl/blob/64f071fb65b837fd65f7847504875d1f5b0d5b27/src/grb_constrs.jl#L168 is off by one. When the model has no constraints, `start = 1`, but `m = 0`, which causes the assertion to fail. For example: 

```julia
julia> model = Gurobi.Model(Gurobi.Env(), "model")
Academic license - for non-commercial use only
Gurobi Model: model
    type   : LP
    sense  : minimize
    number of variables             = 0
    number of linear constraints    = 0
    number of quadratic constraints = 0
    number of sos constraints       = 0
    number of non-zero coeffs       = 0
    number of non-zero qp objective terms  = 0
    number of non-zero qp constraint terms = 0


julia> Gurobi.get_constrmatrix(model)
ERROR: AssertionError: start <= m
Stacktrace:
 [1] get_constrs(::Gurobi.Model, ::Int64, ::Int64) at /home/rdeits/locomotion/explorations/simpleqp-mpc/packages/v0.6/Gurobi/src/grb_constrs.jl:168
 [2] get_constrmatrix(::Gurobi.Model) at /home/rdeits/locomotion/explorations/simpleqp-mpc/packages/v0.6/Gurobi/src/grb_constrs.jl:163
```

I'll submit a fix.

### PR DESCRIPTION
**Pull request by rdeits**
fixes #142

### CODE REVIEW

**Comment by rdeits** [comment]
Sure, good idea

**Comment by rdeits** [comment]
done

**Comment by odow** [comment]
Cool. Tests pass yeah?

**Comment by rdeits** [comment]
yup:

```
Test Summary:                  | Pass  Total
Empty constraints (Issue #142) |    2      2
INFO: Gurobi tests passed
```

**Pull request merged**
