### PR TITLE
Cache ObjVal and ObjBound attributes after solve

### LINKED ISSUE #209: [MOI] Changing bounds etc invalidates stored solution
I tried to use Gurobi with https://github.com/lanl-ansi/Juniper.jl, and ran into this bug
```julia
using Gurobi
const MOI = Gurobi.MOI

model = Gurobi.Optimizer()
x = MOI.add_variable(model)
c = MOI.add_constraint(model, MOI.SingleVariable(x), MOI.GreaterThan(0.0))
MOI.set(model, MOI.ObjectiveFunction{MOI.SingleVariable}(), MOI.SingleVariable(x))
MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE)
MOI.optimize!(model)

# Can query the objective value
MOI.get(model, MOI.ObjectiveValue())

# Change a variable bound. The change is cached for update
MOI.set(model, MOI.ConstraintSet(), c, MOI.GreaterThan(1.0))

# Calling `get` forces an update
MOI.get(model, MOI.ConstraintSet(), c)

# Invalidating the stored objective :(
MOI.get(model, MOI.ObjectiveValue())
```
Error is
```Julia
ERROR: Gurobi.GurobiError(10005, "Unable to retrieve attribute 'ObjVal'")
```

I'm not sure what we should do, probably cache the objective value. And maybe objective bound, etc? The primal and dual solutions get cached by LQOI after `optimize!`, so these aren't affected.

cc @ccoffrin @Wikunia

### PR DESCRIPTION
**Pull request by odow**
Closes #209.

The bigger question at a MOI level is: should you still be able to query solution attributes after modifying the model?

cc @mlubin @blegat 

Tests passing locally
image

### CODE REVIEW

**Comment by blegat** [comment]
Good question, I am not sure what's best

**Comment by mlubin** [comment]
I don't think we should guarantee this if it implies that a majority of solver wrappers have to add caching code for all solution attributes. After you modify a model, it's fair to not have access to attributes that are set by `optimize!`.

**Comment by odow** [comment]
So then the follow-up question is: should we merge this or change Juniper? Other MIP solvers like GLPK work. I haven't tried CPLEX though.

**Comment by blegat** [comment]
It seems better to change Juniper

**Pull request closed without merging**
