### PR TITLE
updates to MOI 06

### PR DESCRIPTION
**Pull request by vitornesello**
Updates to support MOI 0.6. Tests passing on OSX for Julia 0.6, 0.7 and 1.0.

### CODE REVIEW

**Comment by mlubin** [comment]
LGTM. Needs to be manually tested before we we release.

**Comment by vitornesello** [comment]
@odow I can comment, but are these important tests?

**Comment by odow** [comment]
The tests fail on v1 so not sure how they're passing on OSX??? This is with MathProgBase v0.7.5.
```julia
SOC1A: Error During Test at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:250
  Got exception outside of a @test
  UndefVarError: speye not defined
  Stacktrace:
   [1] loadproblem!(::MathProgBase.SolverInterface.LPQPtoConicBridge, ::Array{Float64,1}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Any,1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\src\SolverInterface\lpqp_to_conic.jl:140
   [2] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:232 [inlined]
   [3] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [4] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:224 [inlined]
   [5] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [6] #conicSOCtest#4(::Bool, ::Float64, ::Function, ::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:223
   [7] conicSOCtest(::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:218
   [8] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\MathProgBase\mathprog.jl:40
   [9] include at .\boot.jl:317 [inlined]
   [10] include_relative(::Module, ::String) at .\loading.jl:1038
   [11] include at .\sysimg.jl:29 [inlined]
   [12] include(::String) at .\loading.jl:1073
   [13] top-level scope at none:0
   [14] eval at .\boot.jl:319 [inlined]
   [15] evalfile(::String, ::Array{String,1}) at .\loading.jl:1069 (repeats 2 times)
   [16] macro expansion at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:32 [inlined]
   [17] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [18] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:31
   [19] include at .\boot.jl:317 [inlined]
   [20] include_relative(::Module, ::String) at .\loading.jl:1038
   [21] include(::Module, ::String) at .\sysimg.jl:29
   [22] include(::String) at .\client.jl:388
   [23] top-level scope at none:0
   [24] eval(::Module, ::Any) at .\boot.jl:319
   [25] macro expansion at .\logging.jl:317 [inlined]
   [26] exec_options(::Base.JLOptions) at .\client.jl:219
   [27] _start() at .\client.jl:421
SOC2: Error During Test at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:310
  Got exception outside of a @test
  UndefVarError: speye not defined
  Stacktrace:
   [1] loadproblem!(::MathProgBase.SolverInterface.LPQPtoConicBridge, ::Array{Int64,1}, ::Array{Int64,2}, ::Array{Float64,1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\src\SolverInterface\lpqp_to_conic.jl:140
   [2] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:239 [inlined]
   [3] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [4] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:224 [inlined]
   [5] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [6] #conicSOCtest#4(::Bool, ::Float64, ::Function, ::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:223
   [7] conicSOCtest(::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:218
   [8] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\MathProgBase\mathprog.jl:40
   [9] include at .\boot.jl:317 [inlined]
   [10] include_relative(::Module, ::String) at .\loading.jl:1038
   [11] include at .\sysimg.jl:29 [inlined]
   [12] include(::String) at .\loading.jl:1073
   [13] top-level scope at none:0
   [14] eval at .\boot.jl:319 [inlined]
   [15] evalfile(::String, ::Array{String,1}) at .\loading.jl:1069 (repeats 2 times)
   [16] macro expansion at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:32 [inlined]
   [17] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [18] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:31
   [19] include at .\boot.jl:317 [inlined]
   [20] include_relative(::Module, ::String) at .\loading.jl:1038
   [21] include(::Module, ::String) at .\sysimg.jl:29
   [22] include(::String) at .\client.jl:388
   [23] top-level scope at none:0
   [24] eval(::Module, ::Any) at .\boot.jl:319
   [25] macro expansion at .\logging.jl:317 [inlined]
   [26] exec_options(::Base.JLOptions) at .\client.jl:219
   [27] _start() at .\client.jl:421
SOC2A: Error During Test at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:345
  Got exception outside of a @test
  UndefVarError: speye not defined
  Stacktrace:
   [1] loadproblem!(::MathProgBase.SolverInterface.LPQPtoConicBridge, ::Array{Int64,1}, ::Array{Int64,2}, ::Array{Float64,1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\src\SolverInterface\lpqp_to_conic.jl:140
   [2] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1088 [inlined]
   [3] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:224 [inlined]
   [4] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [5] #conicSOCtest#4(::Bool, ::Float64, ::Function, ::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:223
   [6] conicSOCtest(::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:218
   [7] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\MathProgBase\mathprog.jl:40
   [8] include at .\boot.jl:317 [inlined]
   [9] include_relative(::Module, ::String) at .\loading.jl:1038
   [10] include at .\sysimg.jl:29 [inlined]
   [11] include(::String) at .\loading.jl:1073
   [12] top-level scope at none:0
   [13] eval at .\boot.jl:319 [inlined]
   [14] evalfile(::String, ::Array{String,1}) at .\loading.jl:1069 (repeats 2 times)
   [15] macro expansion at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:32 [inlined]
   [16] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [17] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:31
   [18] include at .\boot.jl:317 [inlined]
   [19] include_relative(::Module, ::String) at .\loading.jl:1038
   [20] include(::Module, ::String) at .\sysimg.jl:29
   [21] include(::String) at .\client.jl:388
   [22] top-level scope at none:0
   [23] eval(::Module, ::Any) at .\boot.jl:319
   [24] macro expansion at .\logging.jl:317 [inlined]
   [25] exec_options(::Base.JLOptions) at .\client.jl:219
   [26] _start() at .\client.jl:421
SOCRotated1A: Error During Test at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:476
  Got exception outside of a @test
  MethodError: no method matching setindex_shape_check(::Float64, ::Int64)
  Closest candidates are:
    setindex_shape_check(!Matched::AbstractArray{#s57,1} where #s57, ::Integer) at indices.jl:193
    setindex_shape_check(!Matched::AbstractArray{#s57,1} where #s57, ::Integer, !Matched::Integer) at indices.jl:196
    setindex_shape_check(!Matched::AbstractArray{#s57,2} where #s57, ::Integer, !Matched::Integer) at indices.jl:200
    ...
  Stacktrace:
   [1] macro expansion at .\multidimensional.jl:641 [inlined]
   [2] _unsafe_setindex!(::IndexLinear, ::Array{Float64,1}, ::Float64, ::Array{Int64,1}) at .\multidimensional.jl:636
   [3] _setindex! at .\multidimensional.jl:631 [inlined]
   [4] setindex! at .\abstractarray.jl:998 [inlined]
   [5] loadproblem!(::MathProgBase.SolverInterface.LPQPtoConicBridge, ::Array{Float64,1}, ::Array{Float64,2}, ::Array{Float64,1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}, ::Array{Tuple{Symbol,UnitRange{Int64}},1}) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\src\SolverInterface\lpqp_to_conic.jl:157
   [6] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:453 [inlined]
   [7] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [8] macro expansion at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:446 [inlined]
   [9] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [10] #conicSOCRotatedtest#5(::Bool, ::Float64, ::Function, ::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:445
   [11] conicSOCRotatedtest(::GurobiSolver) at C:\Users\Oscar\.julia\packages\MathProgBase\gF9sU\test\conicinterface.jl:439
   [12] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\MathProgBase\mathprog.jl:41
   [13] include at .\boot.jl:317 [inlined]
   [14] include_relative(::Module, ::String) at .\loading.jl:1038
   [15] include at .\sysimg.jl:29 [inlined]
   [16] include(::String) at .\loading.jl:1073
   [17] top-level scope at none:0
   [18] eval at .\boot.jl:319 [inlined]
   [19] evalfile(::String, ::Array{String,1}) at .\loading.jl:1069 (repeats 2 times)
   [20] macro expansion at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:32 [inlined]
   [21] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
   [22] top-level scope at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:31
   [23] include at .\boot.jl:317 [inlined]
   [24] include_relative(::Module, ::String) at .\loading.jl:1038
   [25] include(::Module, ::String) at .\sysimg.jl:29
   [26] include(::String) at .\client.jl:388
   [27] top-level scope at none:0
   [28] eval(::Module, ::Any) at .\boot.jl:319
   [29] macro expansion at .\logging.jl:317 [inlined]
   [30] exec_options(::Base.JLOptions) at .\client.jl:219
   [31] _start() at .\client.jl:421
┌ Warning: Julia Gurobi interface doesn't properly support range (two-sided) constraints. See Gurobi.jl issue #14
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\MPBWrapper.jl:146
Read MPS format model from file C:\Users\Oscar\.julia\dev\Gurobi\test\MathProgBase\test_get_strarray.mps
Reading time = 0.00 seconds
TESTPROB: 3 rows, 3 columns, 6 nonzeros
┌ Warning: Gurobi will silently silently truncate objective coefficients >1.0e100 or <-1.0e100. Current objective coefficient extrema: (1.1e100, 1.1e100)
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\grb_common.jl:84
┌ Warning: Gurobi will silently silently truncate objective coefficients >1.0e100 or <-1.0e100. Current objective coefficient extrema: (-1.1e100, -1.1e100)
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\grb_common.jl:84
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (1.1e30, 1.1e30). Current upper bound extrema: (Inf, Inf)
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\grb_common.jl:88
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (-Inf, -Inf). Current upper bound extrema: (-1.1e30, -1.1e30)
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\grb_common.jl:88
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (-1.1e30, -1.1e30). Current upper bound extrema: (Inf, Inf)
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\grb_common.jl:88
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (-Inf, -Inf). Current upper bound extrema: (1.1e30, 1.1e30)
└ @ Gurobi C:\Users\Oscar\.julia\dev\Gurobi\src\grb_common.jl:88
Test Summary:                                                                                                          | Pass  Error  Total
MathProgBase Tests                                                                                                     |  253      4    257
  LP 01a                                                                                                               |    2             2
  LP 01b                                                                                                               |    2             2
  LP 02                                                                                                                |    2             2
  LP 03                                                                                                                |    8             8
  LP 04                                                                                                                |   13            13
  MIP 01                                                                                                               |    2             2
  QP1                                                                                                                  |    2             2
  QP2                                                                                                                  |    2             2
  QCQP1                                                                                                                |    2             2
  Testing linprog and subfunctions with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0,:InfUnbdInfo=>1))    |   26            26
  Testing LP interface with GurobiSolver(nothing, Any[(:OutputFlag, 0), (:TimeLimit, 100.0)])                          |   88            88
  Testing mixintprog with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0))                                  |    3             3
  Testing quadprog with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0))                                    |    9             9
  Testing SOCP interface with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0))                              |    3             3
  Testing QP duals with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0,:QCPDual=>1))                        |   14            14
  Testing linear problems through conic interface with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0))     |   24            24
  Testing SOC problems through conic interface with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0))        |    6      3      9
    SOC1                                                                                                               |    5             5
    SOC1A                                                                                                              |           1      1
    SOC2                                                                                                               |           1      1
    SOC2A                                                                                                              |           1      1
    SOC3 infeasible                                                                                                    |    1             1
  Testing SOCRotated problems through conic interface with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0)) |    7      1      8
    SOCRotated1                                                                                                        |    6             6
    SOCRotated1A                                                                                                       |           1      1
    SOCRotated2 infeasible                                                                                             |    1             1
  Testing SOCINT problems through conic interface with GurobiSolver(nothing, Base.Iterators.Pairs(:OutputFlag=>0))     |    5             5
  GRB Attributes                                                                                                       |    7             7
  Env                                                                                                                  |    7             7
  Range Constraints                                                                                                    |    2             2
  GRB String Attributes                                                                                                |    2             2
  Large Coefficients                                                                                                   |    8             8
  test_read                                                                                                            |    5             5
ERROR: LoadError: Some tests did not pass: 253 passed, 0 failed, 4 errored, 0 broken.
in expression starting at C:\Users\Oscar\.julia\dev\Gurobi\test\runtests.jl:30
ERROR: Package Gurobi errored during testing

(v1.0) pkg>
```

**Comment by vitornesello** [comment]
@odow I don't know, check out my log:
[gurbitestslog.txt](https://github.com/JuliaOpt/Gurobi.jl/files/2393772/gurbitestslog.txt)

**Comment by mlubin** [comment]
Could we fix the issue in MPB instead of commenting out the tests?

**Comment by vitornesello** [comment]
@mlubin Sure. How do I reproduce the error here?

**Comment by vitornesello** [comment]
Not running probably due to this:
``` julia
# The following tests are not passing on Gurobi 8.0.0 due to known bug
# on infeasibility check of SOC models.
# https://github.com/JuliaOpt/Gurobi.jl/pull/123
if Gurobi.version < v"8.0.0"
    conicSOCtest(GurobiSolver(OutputFlag=0))
    conicSOCRotatedtest(GurobiSolver(OutputFlag=0))
end
```
in file `Gurobi/test/MathProgBase/mathprog.jl:34`

**Comment by vitornesello** [comment]
Apparently the bug was not fixed in 8.0.1: http://www.gurobi.com/resources/documentation/fixes

**Comment by mlubin** [comment]
It's worth double checking if 8.0.1 passes. It could be fixed even if it's not listed in the change log.

**Comment by mlubin** [comment]
(Also running with 8.0.1 will be sufficient to reveal the `speye` issue.)

**Comment by mlubin** [comment]
@odow, could you test again with MPB master?

**Comment by odow** [comment]
All tests pass on MPB master.

**Comment by mlubin** [comment]
I'll merge and tag since this isn't a regression on 0.6 and there's no CI anyway.

**Pull request merged**
