### PR TITLE
Fix broken MPB callback interface

### LINKED ISSUE #159: Gurobi 8.0 problem
Hello, 

I have just installed Gurobi 8.0 and tried to solve an MILP with an Informational callback function. 
After solving, though I get the following error message:

screen shot 2018-09-25 at 13 10 41

Does anyone know what this issue is to due and have hints on how to fix it?

### PR DESCRIPTION
**Pull request by mlubin**
Closes #159 

I'm not able to test this. @chriscoey, @CBongiova please confirm that this fixes the issue.

### CODE REVIEW

**Comment by CBongiova** [comment]
@mlubin just to make sure, since I have never done it: Can I just copy-paste the function at 
https://github.com/JuliaOpt/Gurobi.jl/blob/b36acf4af1c401db0d6a806327a50f1ff08734c4/src/MPBWrapper.jl ? 
Because this has not worked for me...

**Comment by mlubin** [comment]
The `is_windows` issue should be fixed now.

**Comment by odow** [comment]
This is why we need a proper CI with code coverage... I'm seeing Daniel this week.

**Comment by CBongiova** [comment]
> > Can I just copy-paste the revised MPBWrapper into my local MPBWrapper.jl function?
> 
> That's not the cleanest way, but yes. On Julia 1.0 you can `] add Gurobi#mlubin-patch1` instead.
> 
> The `is_windows` issue should be fixed now.

Thanks for the hint about how to add the patch in a cleaner way. I see that the branch has been closed though. So how should I update the MPBWrapper in a clean way now? 

I have tried the new MPBWrapper and I still get an error message with Julia v.1.0 

> UndefVarError: cfunction not defined
setmathprogcallback!(::Gurobi.GurobiMathProgModel) at MPBWrapper.jl:722
macro expansion at logging.jl:307 [inlined]
optimize!(::Gurobi.GurobiMathProgModel) at MPBWrapper.jl:419
#solve#119(::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Model) at solvers.jl:175
solve(::Model) at solvers.jl:150
top-level scope at none:0
include_string(::Module, ::String, ::String) at loading.jl:1005
include_string(::Module, ::String, ::String, ::Int64) at eval.jl:30
(::getfield(Atom, Symbol("##117#123")){String,Int64,String})() at eval.jl:94
withpath(::getfield(Atom, Symbol("##117#123")){String,Int64,String}, ::String) at utils.jl:30
withpath at eval.jl:46 [inlined]
#116 at eval.jl:93 [inlined]
with_logstate(::getfield(Atom, Symbol("##116#122")){String,Int64,String}, ::Base.CoreLogging.LogState) at logging.jl:397
with_logger at logging.jl:493 [inlined]
#115 at eval.jl:92 [inlined]
hideprompt(::getfield(Atom, Symbol("##115#121")){String,Int64,String}) at repl.jl:85
macro expansion at eval.jl:91 [inlined]
(::getfield(Atom, Symbol("##114#120")){Dict{String,Any}})() at task.jl:85

**Comment by CBongiova** [comment]
> this PR does resolve the error I was seeing (on Julia 0.6.4 at least)
> thanks!

@mlubin fyi I have re-installed Julia v.0.6.4.  The new MPBWrapper works well for this Julia version also for me (the error I posted before is related to Julia v.1.0)

**Pull request merged**
