### PR TITLE
terminate instead of throwing error when user exits from callback

### PR DESCRIPTION
**Pull request by mlubin**
Ref https://groups.google.com/forum/#!topic/julia-opt/BJ37w-EgmBA

### CODE REVIEW

**Comment by mlubin** [comment]
Don't merge yet, needs further discussion on if we allow separate codes for error and user limits.

**Comment by joehuchette** [comment]
ping @mlubin

**Comment by mlubin** [comment]
@joehuchette, could you handle the cplex version?

**Comment by joehuchette** [comment]
https://github.com/JuliaOpt/CPLEX.jl/commit/4ad6ba98750bbea7b0b086f080dd932f26a2a924

**Pull request merged**
