### PR TITLE
Revert QCPDual to default

### LINKED ISSUE #309: On QCQP in Gurobi v9.0
I noticed the following,
- `QCPDual` seems to be set to 1 by default, which differs from Gurobi's documented semantics
- When `QCPDual` is not set, the SolveTime attribute seems to return only the dual solve time and not the overall solve time for primal and dual.

### PR DESCRIPTION
**Pull request by odow**
Closes #309.

cc @ccoffrin

### CODE REVIEW

**Comment by odow** [comment]
I guess this is technically a breaking change.

**Comment by blegat** [comment]
Yes, we can do a minor version bump

**Comment by odow** [comment]
If we're reverting `QCPDual`, we should also revert `InfUnbdInfo` and break multiple things at the same time:
image

**Comment by ccoffrin** [comment]
if "revert `InfUnbdInfo`" means going back to Gurobi's defaults, I agree!

**Pull request merged**
