### PR TITLE
Support hierarchical multi-objectives

### PR DESCRIPTION
**Pull request by cossio**
Fix https://github.com/JuliaOpt/Gurobi.jl/issues/82.

Update of https://github.com/JuliaOpt/Gurobi.jl/pull/83.

### CODE REVIEW

**Comment by blegat** [comment]
@cossio I have added 2 line comments

**Comment by cossio** [comment]
@blegat I don't see it.

**Comment by blegat** [comment]
I will write them below:
* We should throw an error if the user try to do `set_multiobj!` with an id exceeding what was set by `set_multiobj_n!` to avoid Gurobi to e.g. segfault.
* I would rather use 1-based indexing for the id even if Gurobi uses 0-based indexing.

**Comment by cossio** [comment]
I'll get back to this next wek.

**Comment by ciko92** [comment]
Hi, I'm very interesting in this pull request. Will it be accepted soon?

**Comment by blegat** [comment]
@cossio Are you planning to rebase this PR and reply to the comments sometime soon ?

**Comment by cossio** [comment]
@blegat  I don't have Gurobi anymore, so I can't test this for the moment, sorry. I am planning on getting Gurobi again soon, but can't promise anything right now. If someone else wishes to do it, fell free to use my code here to write something better. Thanks.

**Comment by joehuchette** [comment]
Closed in lieu of #115

**Pull request closed without merging**
