### PR TITLE
Update of README file in response to Issue #73

### PR DESCRIPTION
**Pull request by gdowdy3**
https://github.com/JuliaOpt/Gurobi.jl/issues/73

### CODE REVIEW

**Comment by odow** [comment]
You don't have to pass an `env` to the JuMP model. You might just want to add the link to the part where it discusses sharing multiple `env`s (https://github.com/JuliaOpt/Gurobi.jl#reusing-the-same-gurobi-environment-for-multiple-solves) near the JuMP example.

**Comment by odow** [comment]
Or you could add something like
```julia
m = Model(solver=GurobiSolver())
# you can also use an existing Gurobi.Env as follows
# env = Gurobi.Env()
# setparam!(env, name, v) 
# m = Model(solver=GurobiSolver(env))
```

**Comment by odow** [comment]
While you're at it, the example should have 
```julia
using JuMP, Gurobi
```
as the first line.

**Comment by gdowdy3** [comment]
@odow, I understand that I don't have pass the `env` in order to construct the model and then solve the optimization problem.  But it seems that passing the environment is necessary if I want to modify the solver options - for example to remove preprocessing.  Do you agree?

**Comment by odow** [comment]
You can also pass options as keywords. i.e.:
```julia
m=Model(solver=GurobiSolver(Presolve=0))
```
Here is where they get mapped into `setparam!` calls: https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/GurobiSolverInterface.jl#L36

**Comment by gdowdy3** [comment]
That may be true.  The point is: the README is inconsistent inconsistent in this section.  It suggests that every example has a preamble in which the `env` is modified, but then Example 1.4 does not make use of this modified environment.

**Comment by odow** [comment]
Okay now I see! How about you remove that part and just give the full preamble in each example with the example of setting `Presolve` to zero? For examples 1.1 and 1.2 it would be via the `env` and for 1.3 and 1.4 it would be via the `GurobiSolver` keyword. Thanks for clarifying this!

**Comment by gdowdy3** [comment]
I feel that the README is clear enough if we just add `env` to Examples 1.3 and 1.4 as I've done.

**Comment by mlubin** [comment]
I don't think we should be encouraging use of Env by default in the cases
where passing keywords to GurobiSolver works. The main use case of Env is
to manage license issues where the number of simultaneous solves is limited.

On Dec 18, 2016 16:35, "gdowdy3" <notifications@github.com> wrote:

I feel that the README is clear enough if we just add env to Examples 1.3
and 1.4 as I've done.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaOpt/Gurobi.jl/pull/74#issuecomment-267848560>, or mute
the thread

**Pull request closed without merging**
