### PR TITLE
MOI.get() and MOI.set() for variable attributes

### PR DESCRIPTION
**Pull request by fa-bien**
MOI support for setting and getting variable attributes. This is similar to what has been done for constraint attributes in https://github.com/JuliaOpt/Gurobi.jl/pull/243

### CODE REVIEW

**Comment by fa-bien** [comment]
All 7 tests pass on my computer!

**Comment by odow** [comment]
Great! But just for clarity sake, could you please run the full tests via `] test Gurobi`, and post a screen-shot like: https://github.com/JuliaOpt/Gurobi.jl/pull/231#issuecomment-522595863

**Comment by fa-bien** [comment]
Screen Shot 2019-09-07 at 05 15 09
Screen Shot 2019-09-07 at 05 15 31

Here are two screenshots showing the test summary, as well as the detail for the new tests. It does fail somewhere but that is unrelated to the pull request; it also happens on the master branch (at least on my computer).

**Comment by odow** [comment]
I can't reproduce the failure. Is everything updated? Can you post the full error?

**Comment by fa-bien** [comment]
Screen Shot 2019-09-08 at 20 54 12

This is with MOI 0.9.2 and Gurobi 0.7.2, Julia 1.2. I get a similar error with Julia 1.1.

**Comment by odow** [comment]
I'm on MacOS with the same versions as you. What is `Gurobi.version`?

It's looking like it isn't doing the modification correctly.

**Comment by fa-bien** [comment]
`Gurobi.version` evaluates to `v"8.0.1"`

**Comment by odow** [comment]
From the [Gurobi release notes](https://www.gurobi.com/resource/fixes/), version 8.1.0 (from 8.0.1)
> Fixed issue with wrong optimal value when objective constant is modified after having solved the model.

You should update your version of Gurobi.

**Comment by fa-bien** [comment]
Indeed, sorry about that. Here is the screenshot when using Gurobi 8.1.1, no failure this time.

Screen Shot 2019-09-08 at 23 03 13

**Comment by odow** [comment]
Great! Thanks for this.

**Pull request merged**
