### PR TITLE
Compute IIS

### PR DESCRIPTION
**Pull request by dourouc05**
Following https://github.com/JuliaOpt/JuMP.jl/issues/1035: implement IIS support in a third package. 

The low-level part was already done here, so I just added the MOI part (which required accessing the error code from the C API).

### CODE REVIEW

**Comment by dourouc05** [comment]
Should this be merged, now?

**Comment by odow** [comment]
Can you confirm that the tests pass?

**Comment by dourouc05** [comment]
I tested with the last commit (all packages being up to date, Julia 1.1.0 and 1.1.1). Unfortunately, I don't have a Gurobi license on this PC to test it right now…

**Comment by antonhinneck** [comment]
I will check, why the tests are failing:

image

**Comment by dourouc05** [comment]
I guess the best thing to do is just to disable the linear10b test case, with the same justification as linear10 (https://github.com/JuliaOpt/MathOptInterface.jl/blob/52988f71b95505a817ea99c7d7032ba40cc97f8f/src/Test/contlinear.jl#L1316: also ranged constraints). I just added a commit to do so. Is it better?

**Comment by antonhinneck** [comment]
Test Summary: | Pass  Total
C API                |   70     70

Test Summary:          | Pass  Total
MathProgBase Tests |  189    189

Test Summary:               | Pass  Total
MathOptInterface Tests | 1584   1584

Now, all tests pass. 
How is the branch now conflicting with the upstream/master?

**Comment by dourouc05** [comment]
Actually, the linear10b test is already disabled on master, but without a line feed. This is solved, then! Thanks :)!

**Comment by antonhinneck** [comment]
ok :) 
Final console log for reference:

[ Info: Recompiling stale cache file C:\Users\Anton Hinneck\.julia\compiled\v1.0\Gurobi\do9v6.ji for Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
Academic license - for non-commercial use only
...
Academic license - for non-commercial use only
Read MPS format model from file C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\test\C\test_get_strarray.mps
Reading time = 0.00 seconds
TESTPROB: 3 rows, 3 columns, 6 nonzeros
Academic license - for non-commercial use only
...
Academic license - for non-commercial use only
**Test Summary: | Pass  Total
C API         |   70     70**
Academic license - for non-commercial use only
...
Academic license - for non-commercial use only
┌ Warning: Gurobi will silently silently truncate objective coefficients >1.0e100 or <-1.0e100. Current objective coefficient extrema: (1.1e100, 1.1e100)
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\grb_common.jl:84
Academic license - for non-commercial use only
┌ Warning: Gurobi will silently silently truncate objective coefficients >1.0e100 or <-1.0e100. Current objective coefficient extrema: (-1.1e100, -1.1e100)
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\grb_common.jl:84
Academic license - for non-commercial use only
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (1.1e30, 1.1e30). Current upper bound extrema: (Inf, Inf)
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\grb_common.jl:88
Academic license - for non-commercial use only
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (-Inf, -Inf). Current upper bound extrema: (-1.1e30, -1.1e30)
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\grb_common.jl:88
Academic license - for non-commercial use only
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (-1.1e30, -1.1e30). Current upper bound extrema: (Inf, Inf)
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\grb_common.jl:88
Academic license - for non-commercial use only
┌ Warning: Gurobi has implicit variable bounds of [-1e30, 1e30]. Settings variable bounds outside this can cause infeasibility or unboundedness. Current lower bound extrema: (-Inf, -Inf). Current upper bound extrema: (1.1e30, 1.1e30)
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\grb_common.jl:88
Academic license - for non-commercial use only
┌ Warning: Julia Gurobi interface doesn't properly support range (two-sided) constraints. See Gurobi.jl issue #14
└ @ Gurobi C:\Users\Anton Hinneck\.julia\packages\Gurobi\dlJep\src\MPB_wrapper.jl:146
Academic license - for non-commercial use only
...
Academic license - for non-commercial use only
┌ Warning: Element type Int64 does not have an infinite value. Note that this may artifically introduce ranged (two-sided) constraints. To avoid this, consider casting the problem data to Float64.
└ @ MathProgBase.HighLevelInterface C:\Users\Anton Hinneck\.julia\packages\MathProgBase\rVlFR\src\HighLevelInterface\HighLevelInterface.jl:9
Academic license - for non-commercial use only
┌ Warning: Element type Int64 does not have an infinite value. Note that this may artifically introduce ranged (two-sided) constraints. To avoid this, consider casting the problem data to Float64.
└ @ MathProgBase.HighLevelInterface C:\Users\Anton Hinneck\.julia\packages\MathProgBase\rVlFR\src\HighLevelInterface\HighLevelInterface.jl:9
Academic license - for non-commercial use only
┌ Warning: Element type Int64 does not have an infinite value. Note that this may artifically introduce ranged (two-sided) constraints. To avoid this, consider casting the problem data to Float64.
└ @ MathProgBase.HighLevelInterface C:\Users\Anton Hinneck\.julia\packages\MathProgBase\rVlFR\src\HighLevelInterface\HighLevelInterface.jl:9
Academic license - for non-commercial use only
┌ Warning: Element type Int64 does not have an infinite value. Note that this may artifically introduce ranged (two-sided) constraints. To avoid this, consider casting the problem data to Float64.
└ @ MathProgBase.HighLevelInterface C:\Users\Anton Hinneck\.julia\packages\MathProgBase\rVlFR\src\HighLevelInterface\HighLevelInterface.jl:9
Academic license - for non-commercial use only
┌ Warning: Element type Int64 does not have an infinite value. Note that this may artifically introduce ranged (two-sided) constraints. To avoid this, consider casting the problem data to Float64.
└ @ MathProgBase.HighLevelInterface C:\Users\Anton Hinneck\.julia\packages\MathProgBase\rVlFR\src\HighLevelInterface\HighLevelInterface.jl:9
Academic license - for non-commercial use only
┌ Warning: Element type Int64 does not have an infinite value. Note that this may artifically introduce ranged (two-sided) constraints. To avoid this, consider casting the problem data to Float64.
└ @ MathProgBase.HighLevelInterface C:\Users\Anton Hinneck\.julia\packages\MathProgBase\rVlFR\src\HighLevelInterface\HighLevelInterface.jl:9
Academic license - for non-commercial use only
...
Academic license - for non-commercial use only
**Test Summary:      | Pass  Total
MathProgBase Tests |  189    189**
Academic license - for non-commercial use only
...
Academic license - for non-commercial use only

IIS computed: 0 constraints and 2 bounds
IIS runtime: 0.00 seconds
0
Academic license - for non-commercial use only

IIS computed: 2 constraints and 0 bounds
IIS runtime: 0.00 seconds
Academic license - for non-commercial use only

IIS computed: 0 constraints and 2 bounds
IIS runtime: 0.00 seconds
Academic license - for non-commercial use only

IIS computed: 0 constraints and 2 bounds
IIS runtime: 0.00 seconds
Academic license - for non-commercial use only

IIS computed: 1 constraints and 2 bounds
IIS runtime: 0.00 seconds
Academic license - for non-commercial use only

IIS computed: 1 constraints and 2 bounds
IIS runtime: 0.00 seconds
Academic license - for non-commercial use only

IIS computed: 1 constraints and 2 bounds
IIS runtime: 0.00 seconds
Academic license - for non-commercial use only
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0      handle free variables                          0s
IIS runtime: 0.00 seconds
**Test Summary:          | Pass  Total
MathOptInterface Tests | 1584   1584**
julia>

**Pull request merged**
